name: Cache

on:
  schedule:
    - cron: '5 * * * *'

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: /
          key: ff1o9797cb
          restore-keys: ff1o9797cb,iiiphda682986,hugbsifsd,
          upload-chunk-size: 1000000

