name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi! Welcome to the repository. Thank you for listing your issue'
        pr-message: 'Hey! Thank for contributing to the community.Your code is appreciated.'
        
